# Используем Node.js как базовый образ
FROM node:18

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем package.json и package-lock.json
COPY ./package*.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем весь проект
COPY ./ ./

# Сборка React-приложения
RUN npm run build

# Устанавливаем сервер для хостинга статики
RUN npm install -g serve

# Открываем порт для React
EXPOSE 3000

# Запуск React приложения
CMD ["serve", "-s", "build"]
