services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - "3001:3001"
    volumes:
      - ./server:/app
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=kurs
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    working_dir: /app
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

  db:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kurs
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
